---
# $Author$
# $Date$
# $Source$

# create-output-file tasks file for mdrotthoff.sshknownhosts
- name: Display the enter create-output-file.yml message
  debug:
    msg: 'Enter create-output-file.yml'
  connection:  local
  tags:
  - debug
  - never

- name: Ensure the known host directory exists
  file:
    path:      "{{ sshknownhosts_file_path }}"
    state:     directory
    recurse:   true
  connection:  local
  tags:
  - sshknownhosts

- name: Ensure the known host file exists
  copy:
    content:   ""
    dest:      "{{ sshknownhosts_file_path }}/{{ sshknownhosts_file_name }}"
    force:     no
  connection:  local
  tags:
  - sshknownhosts

- name: Ensure the known host file ownership and permissions are correct
  file:
    path:      "{{ sshknownhosts_file_path }}/{{ sshknownhosts_file_name }}"
    state:     file
    owner:     "{{ sshknownhosts_file_owner | default(omit) }}"
    group:     "{{ sshknownhosts_file_group | default(omit) }}"
    mode:      "{{ sshknownhosts_file_mode | default(omit) }}"
  connection:  local
  tags:
  - sshknownhosts

- name: Display the exit create-output-file.yml message
  debug:
    msg: 'Exit create-output-file.yml'
  connection:  local
  tags:
  - debug
  - never
